PACKAGE_NAME="rtmouse"
PACKAGE_VERSION="1.0"

MAKE[0]="bash src/drivers/dkms_make.sh ${kernelver}"
CLEAN="bash src/drivers/dkms_make.sh ${kernelver} clean"

BUILT_MODULE_LOCATION[0]="src/drivers/"
BUILT_MODULE_NAME[0]="rtmouse"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"
