KERNEL_SRC := $(HOME)/repo/raspberrypi/linux
ARCH := arm
CROSS_COMPILE := $(HOME)/repo/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-
BUILD_DIR = `pwd`

MODULES := rtmouse.o

obj-m := $(MODULES)

all: $(MODULES:.o=.ko)

rtmouse.ko: rtmouse.c
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(BUILD_DIR) V=0 modules

clean:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KERNEL_SRC) M=$(BUILD_DIR) V=0 clean

