MODULE:= rtmouse
EXTRA_CFLAGS := -I$(PWD)/include
obj-m:= $(MODULE).o
clean-files:= *.o *.ko *.mod.[co] *~

LINUX_SRC_DIR:=/usr/src/linux
VERBOSE:=0

rtmouse.ko: rtmouse.c
	make -C $(LINUX_SRC_DIR) M=$(shell pwd) V=$(VERBOSE) modules

clean:
	make -C $(LINUX_SRC_DIR) M=$(shell pwd) V=$(VERBOSE) clean
