MODULE:= rtmouse
obj-m:= $(MODULE).o
clean-files:= *.o *.ko *.mod.[co] *~

LINUX_SRC_DIR:=/usr/src/linux-headers-$(shell uname -r)
VERBOSE:=0

rtmouse.ko: rtmouse.c rtmouse.h
	make -C $(LINUX_SRC_DIR) M=$(shell pwd) V=$(VERBOSE) modules

clean:
	make -C $(LINUX_SRC_DIR) M=$(shell pwd) V=$(VERBOSE) clean

install: rtmouse.ko
	cp ../../50-rtmouse.rules /etc/udev/rules.d/

uninstall:
	rm /etc/udev/rules.d/50-rtmouse.rules

#Reference: http://www.devdrv.co.jp/linux/kernel26-makefile.htm
