#Reference: http://www.devdrv.co.jp/linux/kernel26-makefile.htm
TARGET:= rtmouse.ko

all: ${TARGET}

rtmouse.ko: rtmouse.c
	make -C /usr/src/linux-headers-`uname -r` M=`pwd` V=1 modules

clean:
	make -C /usr/src/linux-headers-`uname -r` M=`pwd` V=1 clean

obj-m:= rtmouse.o

clean-files := *.o *.ko *.mod.[co] *~
