name: Lint

on:
  push:
    branches:
      - master
    paths:
    - 'src/drivers/**'
    - '.github/workflows/**'
    - '.test/lint.sh'
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'src/drivers/**'
    - '.github/workflows/**'
    - '.test/lint.sh'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Lint
        run: |
          ./.test/lint.sh

